name: TEST-PyPI-PUBLISH #NOTE Rename to 'PyPI Publish' before PR
on:
  repository_dispatch:
    types: [trigger-upload]
  push:
    paths:
      - '/src/syngen/VERSION'
  workflow_run:
    workflows: ["TEST-BUILD"]
    types:
      - completed
jobs:
  PyPI-syngen-workflow:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python '3.8'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt install python3.8-venv -y
          python -m pip install --upgrade pip
          pip install build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build Package
        run: |
          python3 -m build .
      - name: Publish package
#        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          print_hash: true
          verbose: true