name: TEST-PIPY-PUBLISH
on: [push]
jobs:
  PIPy-uploading:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          apt install python3.8-venv -y
          python -m pip install --upgrade pip
          pip install build
      - name: Build Package
        run: |
          python3 -m build --wheel
      - name: Publish package
        if: github.event_name == 'push' # && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          print_hash: true
          verbose: true
